name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up .npmrc
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        registry-url: 'https://npm.pkg.github.com'
        # Defaults to the user or organization that owns the workflow file
        scope: '@RICHARD-Quentin'
        
    - name: Run yarn
      shell: bash
      run: yarn
    
    - name: Publish
      shell: bash
      run: yarn publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
