name: Release

on:
  workflow_dispatch:
    inputs:
      version_increment:
        description: 'La version a incrémenter (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
        - 'major'
        - 'minor'
        - 'patch'
        
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Publish to npm
        uses: Libertech-FR/lt-actions/release-npm@main
        with:
          version_increment: ${{ github.event.inputs.version_increment }}
          repository: ${{ github.repository }}
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          package_manager: "npm"

  publish-yarn:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Publish to yarn
        uses: Libertech-FR/lt-actions/release-npm@main
        with:
          version_increment: ${{ github.event.inputs.version_increment }}
          repository: ${{ github.repository }}
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          package_manager: "yarn"
